## 错误处理

flang采用 try catch finally模式处理错误。

~~~
...
try{
a = b/c
}catch{
...
}finally{
...
}

~~~

### 错误类型

所有错误类型都继承自Err类型

+ Err
  + SysErr
    + OutOfMemErr
	+ StackOverflowErr
	+ IndexOutOfRangeErr
	+ DivideByZeroErr
	+ IOErr
  + UserdefinedErr

用户也可以抛出错误

~~~
#[throws(Err)]
func somefunc():Int{
...
throw Err()
...
}
~~~

错误类型定义

~~~


~~~